### ISSUE TITLE
Encryption Issue 

### ISSUE THREAD

**Issue by pedroalbanese** [vmarlier/go-DES#1]
Hi, I compiled the code, but it does not work.. It results no output when encrypt a string

I compiled with go 1.15.3 windows/386 and go 1.11.13 windows/386, in both cases it generates an executable with this error, there is no output.

How to proceed?

Thanks in advance.

**Comment by vmarlier** [comment]
Hello @pedroalbanese,

I think the problem comes from the key, the key used for encryption must be 8 bytes long (or multiple of 8).

I have not yet added the management of keys smaller or larger. It will be done soon 👍 

Thank you for your interest.

**Comment by pedroalbanese** [comment]
But when I do insert an 8 bytes key:

2020/12/05 09:41:06 strconv.ParseUint: parsing "00000000000101111111110101000101
0010100000000000": value out of range

And with 16 characters key also bugs (no output)..

**Comment by vmarlier** [comment]
What is the key you're inserting (I want to reproduce the bug) ?

**Comment by pedroalbanese** [comment]
any 8 digits key:

go-DES -e -b64 "I am a message to encrypt"

What is you initial key:
12345678

2020/12/05 09:43:07 strconv.ParseUint: parsing "0000000000010111111111010100010
0010100000000000": value out of range

**Comment by pedroalbanese** [comment]
keys with another length result in null output

**Comment by vmarlier** [comment]
Ok it's strange behavior.

go run main.go -e -b64 "I am a message to encrypt"        
                                                                                                 
Enter DES encryption key:
12345678

Encrypted Message:
dH9owqRKw5dXCQjCoBASSsOXw5s5P8OvRGLDmcO7wpZjwrTDiipdBwHDt8Ka

**Comment by vmarlier** [comment]
Can you try to pull from the main branch and to rebuild it or use "go run" ?

**Comment by pedroalbanese** [comment]
Now all keys:

H:\PRGM\Linux\go-DES-main>go-DES -e -b64 "I am a message to encrypt"
Enter DES encryption key:
12345678

2020/12/05 10:09:14 strconv.ParseUint: parsing "00000000000101111111110101000
0010100000000000": value out of range

H:\PRGM\Linux\go-DES-main>go-DES -e -b64 "I am a message to encrypt"
Enter DES encryption key:
1234

2020/12/05 10:09:23 strconv.ParseUint: parsing "00000000000101111111110101000
0010100000000000": value out of range

H:\PRGM\Linux\go-DES-main>go-DES -e -b64 "I am a message to encrypt"
Enter DES encryption key:
123456

2020/12/05 10:09:43 strconv.ParseUint: parsing "00000000000101111111110101000
0010100000000000": value out of range

**Comment by vmarlier** [comment]
Ok I'm going to test on a Windows too.
I'll keep you informed.

**Comment by pedroalbanese** [comment]
Thanks!

**Comment by vmarlier** [comment]
Ok so I found there is no bug if I use an amd64 architecture (as you can see below).
But when I build with GOARCH=386 I have the same error.. I need to learn more about the 386 architecture to be able to try to debug, I will keep you informed.

AMD64:
<img width="859" alt="image" src="https://user-images.githubusercontent.com/32210943/101244549-7c060480-3707-11eb-90ac-d75742d59698.png">

386:
<img width="859" alt="image" src="https://user-images.githubusercontent.com/32210943/101244700-3ac22480-3708-11eb-96d9-fa389c9818e1.png">

**Comment by pedroalbanese** [comment]
Thank you for your willingness!
